name: Deploy Portfolio

on:
  push:
    branches:
      - main # Trigger deployment on pushes to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ Setup SSH agent with private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 6️⃣ Add server to known_hosts to prevent host verification errors
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # 7️⃣ Deploy built files to server and restart nginx
      - name: Deploy to server
        env:
          HOST: ${{ secrets.DO_HOST }}
          USER: ${{ secrets.DO_USER }}
        run: |
          rsync -avz --delete ./dist/ $USER@$HOST:/var/www/html/
          ssh $USER@$HOST 'sudo systemctl restart nginx || true'

      # 8️⃣ Optional: verify deployment
      - name: Verify deployment
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "ls -l /var/www/html/"
