name: Deploy Portfolio

on:
  push:
    branches:
      - main # Deploy when changes are pushed to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the project
      - name: Build project
        run: npm run build

      # 5️⃣ Setup SSH agent with private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 6️⃣ Add server to known_hosts to avoid host verification errors
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      # 7️⃣ Deploy files to the server and restart nginx
      - name: Deploy to server
        run: |
          rsync -avz --delete ./dist/ ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/var/www/html/
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} 'sudo systemctl restart nginx || true'
